/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdlib.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//RCC
#define  RCC_BASE   				( uint32_t )( 0x40021000 )
#define  RCC_CR     				*( volatile uint32_t *)( RCC_BASE + 0x0 )
#define  RCC_CFGR   				*( volatile uint32_t *)( RCC_BASE + 0x04 )
#define RCC_APB2ENR                 *( ( volatile uint32_t* )( RCC_BASE + 0x18 ) )

//GPIO
#define GPIOA_BASE                  ( uint32_t )0x40010800
#define GPIOA_CRH                   *( ( volatile uint32_t* )( GPIOA_BASE + 0x04 ) )
#define GPIOA_ODR                   *( ( volatile uint32_t* )( GPIOA_BASE + 0x0C ) )

#define RCC_IOPAEN                  ( 1 << 2 )
#define GPIOA_13                    ( 1 << 13 )

void Clock_Init()
{
	//Bits 7:4 HPRE: AHB prescaler
	//	Set and cleared by software to control the division factor of the AHB clock.
	//	0xxx: SYSCLK not divided
	//	1000: SYSCLK divided by 2
	//	1001: SYSCLK divided by 4
	//	1010: SYSCLK divided by 8
	//	1011: SYSCLK divided by 16
	//	1100: SYSCLK divided by 64
	//	1101: SYSCLK divided by 128
	//	1110: SYSCLK divided by 256
	//	1111: SYSCLK divided by 512
	RCC_CFGR |=	 ( 0b0000 << 4 );

	//Bits 10:8 PPRE1: APB low-speed prescaler (APB1)
    //	Set and cleared by software to control the division factor of the APB low-speed clock
    //	(PCLK1).
    //	Warning: the software has to set correctly these bits to not exceed 36 MHz on this domain.
    //	0xx: HCLK not divided
    //	100: HCLK divided by 2
    //	101: HCLK divided by 4
    //	110: HCLK divided by 8
    //	111: HCLK divided by 16
	RCC_CFGR |=	 ( 0b100 << 8 );


	//	Bits 13:11 PPRE2: APB high-speed prescaler (APB2)
	//	Set and cleared by software to control the division factor of the APB high-speed clock
	//	(PCLK2).
	//	0xx: HCLK not divided
	//	100: HCLK divided by 2
	//	101: HCLK divided by 4
	//	110: HCLK divided by 8
	//	111: HCLK divided by 16
	RCC_CFGR |=	 ( 0b101 << 11 );

}

int main(void)
{
	Clock_Init();

	RCC_APB2ENR |= RCC_IOPAEN;  // enable clock

	GPIOA_CRH &= ~( 7 << 20 );
	GPIOA_CRH |= ( 2 << 20 );   //enable pin as output

	while(1)
	{
		GPIOA_ODR ^= GPIOA_13;      // toggle pin13
		for( int i =0 ; i < 5000 ; i++);  // delay
	}

    /* Loop forever */
	for(;;);
}
